export const headerOptions = [
  { area: ["area", "hubname"] },
  {
    bkt: [
      "bkt",
      "overduebucketnumber",
      "bucket",
      "bucketslab",
      "bktband",
      "dpd",
      "derbucket",
      "cfrbkt",
    ],
  },
  {
    branch: [
      "branch",
      "branchname",
      "locationname",
      "branchnameimptd",
      "location",
      "misbranch",
      "vehicleroute",
      "loanbranch",
      "barnch",
    ],
  },
  {
    "chassis no": [
      "chassisno",
      "chsno",
      "chasisno",
      "chassisnum",
      "chasisnumber",
      "chassisnumber",
      "chassieno",
      "chassno",
      "chassis",
      "chasisnum",
      "chano",
      "chesisnumber",
      "chassino",
    ],
  },
  {
    "contract no": [
      "contractno",
      "fileno",
      "dealno",
      "agreementno",
      "loanno",
      "contractnumbe",
      "contno",
      "loanrefno",
      "lan",
      "dealnumber",
      "agrino",
      "conno",
      "agrnumber",
      "agrno",
    ],
  },
  {
    "customer name": [
      "customername",
      "customer",
      "name",
      "nameofclient",
      "custname",
      "cname",
      "nameofcustomer",
      "partyname",
      "cmname",
      "nameofthecustomer",
    ],
  },
  {
    "engine no": [
      "engineno",
      "engno",
      "enginenum",
      "eng",
      "enginenumber",
      "engine",
      "engnno",
    ],
  },
  { "ex name": ["exname", "executivename"] },
  { financer: ["financer", "financier", "financename"] },
  { gv: ["gv"] },
  {
    level1: [
      "level1",
      "contperson1",
      "supervisorname1",
      "1stcontactperson",
      "firstlevelcontactpersonname",
      "confirmationperson1",
    ],
  },
  {
    level1con: [
      "level1con",
      "mobno",
      "mobileno",
      "contactnumaber1st",
      "level1contactnos",
      "mobile",
      "confirmation1mobileno",
    ],
  },
  {
    level2: [
      "level2",
      "contperson2",
      "supervisorname2",
      "secondlevelcontactname",
      "confirmationperson2",
    ],
  },
  { level2con: ["level2con", "level2contactnos", "confirmation2mobileno"] },
  { level3: ["level3", "supervisorname3", "confirmationperson3"] },
  { level3con: ["level3con", "level3contactnos", "confirmation3mobileno"] },
  { level4: ["level4"] },
  { level4con: ["level4con", "level4contactnos"] },
  {
    "mek and model": [
      "mekandmodel",
      "vehiclemodel",
      "model",
      "make",
      "vehmodel",
      "product",
      "vehiclemodelno",
      "vehiclemfg/model",
      "makemodel",
      "vehicledescription",
      "manufacturerdesc",
      "productname",
      "assetdescription",
      "make/model",
    ],
  },
  { od: ["od", "overdueamount"] },
  { poss: ["poss", "pos"] },
  {
    "rc no": [
      "rcno",
      "regdnum",
      "regno",
      "vehicleregistrationnumber",
      "vehicleno",
      "rcnumber",
      "vehno",
      "regnum",
      "rcbookno",
      "registrationno",
      "regnno",
      "veichelno",
      "rc",
      "vehid",
      "regnumber",
      "regnnumber",
      "registerno",
      "vehiclenumber",
      "vehicleregno",
    ],
  },
  { region: ["region", "state", "zone"] },
  { ses17: ["ses17", "sec17available"] },
  { ses9: ["ses9", "sec9available"] },
  { tbr: ["tbr", "tbrflag"] },
  // ── Additional fields from the new CSV format ──────────────────────────
  {
    "customer contact nos": [
      "customercontactnos",
      "customermobile",
      "customerphonenumber",
      "customerphone",
      "custphone",
      "custmobile",
      "customerno",
    ],
  },
  {
    "customer address": [
      "customeraddress",
      "address",
      "custaddress",
      "custaddr",
      "customeraddr",
    ],
  },
  { seasoning: ["seasoning"] },
  {
    "sender mail id 1": [
      "sendermailid1",
      "sendermail1",
      "email1",
      "senderemail1",
    ],
  },
  {
    "sender mail id 2": [
      "sendermailid2",
      "sendermail2",
      "email2",
      "senderemail2",
    ],
  },
  { toss: ["toss"] },
  { remark: ["remark", "remarks", "comment", "comments", "note", "notes"] },
  { "is released": ["isreleased", "released"] },
];



export const headerOptionsOfServer = [
  "area",
  "bkt",
  "branch",
  "chassis_no",
  "contract_no",
  "customer_name",
  "engine_no",
  "ex_name",
  "financer",
  "gv",
  "level1",
  "level1con",
  "level2",
  "level2con",
  "level3",
  "level3con",
  "level4",
  "level4con",
  "mek_and_model",
  "od",
  "poss",
  "rc_no",
  "region",
  "ses17",
  "ses9",
  "tbr",
];

export const validRcRegexType = [
  /^[0-9]{2}[A-Za-z]{2}[0-9]{4}[A-Za-z]{1,2}$/,
  /^[A-Za-z]{2}[0-9]{2}[A-Za-z]{1,4}[0-9]{4}$/,
  /^[A-Za-z]{2}[0-9]{6}$/,
];
